### ISSUE TITLE
iio-sensor-proxy 2.4 fails to build

### ISSUE THREAD

**Issue by david-geiger** [hadess/iio-sensor-proxy#226]
Hi,

On Mageia Cauldron latest iio-sensor-proxy 2.4 fails to build with the following error:

> test-mount-matrix.c:18:4: error: implicit conversion from 'float' to 'double' when passing argument to function [-Werror=double-promotion]
    vecs[0].x, vecs[0].y, vecs[0].z,

[full_build_log.txt](https://github.com/hadess/iio-sensor-proxy/files/1977697/full_build_log.txt)

Regards David

**Comment by jbicha** [comment]
David, I believe your issue is with the [`ax_is_release`](https://github.com/hadess/iio-sensor-proxy/blob/master/configure.ac#L5) line. Change it to [something else](https://www.gnu.org/software/autoconf-archive/ax_is_release.html)

Specifically, you probably don't want `-Wall -Werror` set in a release build.

**Comment by david-geiger** [comment]
So ok! just turn off the Werror compile flags with  --disable-Werror configure option and now it build fine.

Thanks!
